title: Terraform Input Variables
description: Terraform Variables for VCN Prod HUB JDE uas2
schemaVersion: 1.1.0
version: '20251016'
groupings:
- title: Target Tenancy Variables
  variables:
  - ${tenancy_ocid}
  - ${compartment_name}
  - ${compartment_id_in_subtree}
  - ${region}
  - ${project_tag}
- title: VCN Variables
  variables:
  - ${vcn_prod_hub_jde_uas2_display_name}
  - ${vcn_prod_hub_jde_uas2_dns_label}
  - ${vcn_prod_hub_jde_uas2_cidr_block}
- title: Prod HA Private Subnet Configuration Variables
  variables:
  - ${prod_ha_private_subnet_display_name}
  - ${prod_ha_private_subnet_dns_label}
  - ${prod_ha_private_subnet_cidr_block}
  - ${prod_ha_private_subnet_prohibit_internet_ingress}
  - ${prod_ha_private_subnet_prohibit_public_ip_on_vnic}
  - ${prod_ha_private_subnet_project_tag}
- title: Prod Untrust Subnet Configuration Variables
  variables:
  - ${prod_untrust_subnet_display_name}
  - ${prod_untrust_subnet_dns_label}
  - ${prod_untrust_subnet_cidr_block}
  - ${prod_untrust_subnet_prohibit_internet_ingress}
  - ${prod_untrust_subnet_prohibit_public_ip_on_vnic}
  - ${prod_untrust_project_tag}
- title: Prod Management Subnet Configuration Variables
  variables:
  - ${prod_management_subnet_display_name}
  - ${prod_management_subnet_dns_label}
  - ${prod_management_subnet_cidr_block}
  - ${prod_management_subnet_prohibit_internet_ingress}
  - ${prod_management_subnet_prohibit_public_ip_on_vnic}
  - ${prod_management_project_tag}
- title: Prod Trust Subnet Configuration Variables
  variables:
  - ${prod_trust_subnet_display_name}
  - ${prod_trust_subnet_dns_label}
  - ${prod_trust_subnet_cidr_block}
  - ${prod_trust_subnet_prohibit_internet_ingress}
  - ${prod_trust_subnet_prohibit_public_ip_on_vnic}
  - ${prod_trust_project_tag}
- title: VCN Components Variables
  variables:
  - ${vcn_prod_hub_jde_uas2_servicegateway_private_display_name}
  - ${vcn_prod_hub_jde_uas2_natgateway_display_name}
  - ${vcn_prod_hub_jde_uas2_natgateway_block_traffic}
  - ${vcn_prod_hub_jde_uas2_natgateway_public_ip_lifetime}
  - ${vcn_prod_hub_jde_uas2_intgw_display_name}
  - ${vcn_prod_hub_jde_uas2_intgw_enabled}
- title: VCN Route Table Variables
  variables:
  - ${vcn_prod_hub_jde_uas2_routetable_untrust_display_name}
  - ${vcn_prod_hub_jde_uas2_routetable_private_management_display_name}
  - ${vcn_prod_hub_jde_uas2_routetable_private_trust_display_name}
  - ${vcn_prod_hub_jde_uas2_routetable_private_ha_display_name}
- title: DRG Variables
  variables:
  - ${drg_display_name}
  - ${vcn_prod_hub_jde_uas2_drg_attachment_display_name}
- title: Security List Variables
  variables:
  - ${vcn_prod_hub_jde_uas2_seclist_private_trust_display_name}
  - ${vcn_prod_hub_jde_uas2_seclist_private_ha_display_name}
  - ${vcn_prod_hub_jde_uas2_seclist_private_management_display_name}
  - ${vcn_prod_hub_jde_uas2_seclist_untrust_display_name}
  - ${vcn_prod_hub_jde_uas2_seclist_private_is_stateless}
variables:
  tenancy_ocid:
    type: string
    title: Target tenancy OCID
    description: Target tenancy OCID
    required: false
    visible: true
  compartment_name:
    type: string
    title: Compartment Name to deploy the VCN
    description: Compartment Name to deploy the VCN
    required: false
    visible: true
    default: dr_network
  compartment_id_in_subtree:
    type: boolean
    title: Compartment ID in Subtree
    description: Compartment ID in Subtree
    required: false
    visible: false
    default: true
  region:
    type: string
    title: Region
    description: Region
    required: false
    visible: true
    default: us-ashburn-1
  project_tag:
    type: oci:identity:tag:value
    title: Tags to be assigned to resources created by terraform
    description: Tags to be assigned to resources created by terraform
    required: false
    visible: true
  vcn_prod_hub_jde_uas2_display_name:
    type: string
    title: Prod HUB VCN Display Name
    description: Prod HUB VCN Display Name
    required: false
    visible: true
    default: vcn-prod-hub-jde-uas2
  vcn_prod_hub_jde_uas2_dns_label:
    type: string
    title: Prod HUB VCN DNS Label
    description: Prod HUB VCN DNS Label
    required: false
    visible: true
    default: prodhubjdeuas2
  vcn_prod_hub_jde_uas2_cidr_block:
    type: string
    title: Prod HUB VCN Cidr Block
    description: Prod HUB VCN Cidr Block
    required: false
    visible: true
    default: 20.20.0.0/16
  prod_ha_private_subnet_display_name:
    type: string
    title: Prod HA Private Subnet Display Name
    description: Prod HA Private Subnet Display Name
    required: false
    visible: true
    default: sn-prod-hub-ha-uas2
  prod_ha_private_subnet_dns_label:
    type: string
    title: Prod HA Private Subnet DNS Label
    description: Prod HA Private Subnet DNS Label
    required: false
    visible: true
    default: prodhubhauas2
  prod_ha_private_subnet_cidr_block:
    type: string
    title: Prod HA Private Subnet Cidr Block
    description: Prod HA Private Subnet Cidr Block
    required: false
    visible: true
    default: 20.20.0.0/24
  prod_ha_private_subnet_prohibit_internet_ingress:
    type: boolean
    title: Prod HA Private Subnet Access Type (Private or Public)
    description: Prod HA Private Subnet Access Type (Private or Public)
    required: false
    visible: true
    default: true
  prod_ha_private_subnet_prohibit_public_ip_on_vnic:
    type: boolean
    title: Prod HA Private Subnet Access Type (Private or Public)
    description: Prod HA Private Subnet Access Type (Private or Public)
    required: false
    visible: true
    default: true
  prod_ha_private_subnet_project_tag:
    type: oci:identity:tag:value
    title: Tags to be assigned to resources created by terraform
    description: Tags to be assigned to resources created by terraform
    required: false
    visible: true
  prod_untrust_subnet_display_name:
    type: string
    title: Prod Untrust Subnet Display Name
    description: Prod Untrust Subnet Display Name
    required: false
    visible: true
    default: sn-prod-hub-untrust-uas2
  prod_untrust_subnet_dns_label:
    type: string
    title: Prod Untrust Subnet DNS Label
    description: Prod Untrust Subnet DNS Label
    required: false
    visible: true
    default: untrustuas2
  prod_untrust_subnet_cidr_block:
    type: string
    title: Prod Untrust Subnet Cidr Block
    description: Prod Untrust Subnet Cidr Block
    required: false
    visible: true
    default: 20.20.1.0/24
  prod_untrust_subnet_prohibit_internet_ingress:
    type: boolean
    title: Prod Untrust Subnet Access Type (Private or Public)
    description: Prod Untrust Subnet Access Type (Private or Public)
    required: false
    visible: true
    default: false
  prod_untrust_subnet_prohibit_public_ip_on_vnic:
    type: boolean
    title: Prod Untrust Subnet Access Type (Private or Public)
    description: Prod Untrust Subnet Access Type (Private or Public)
    required: false
    visible: true
    default: false
  prod_untrust_project_tag:
    type: oci:identity:tag:value
    title: Tags to be assigned to resources created by terraform
    description: Tags to be assigned to resources created by terraform
    required: false
    visible: true
  prod_management_subnet_display_name:
    type: string
    title: Prod Management Subnet Display Name
    description: Prod Management Subnet Display Name
    required: false
    visible: true
    default: sn-prod-hub-mgmt-uas2
  prod_management_subnet_dns_label:
    type: string
    title: Prod Management Subnet DNS Label
    description: Prod Management Subnet DNS Label
    required: false
    visible: true
    default: prodhubmgmtuas2
  prod_management_subnet_cidr_block:
    type: string
    title: Prod Management Subnet Cidr Block
    description: Prod Management Subnet Cidr Block
    required: false
    visible: true
    default: 20.20.2.0/24
  prod_management_subnet_prohibit_internet_ingress:
    type: boolean
    title: Prod Management Subnet Access Type (Private or Public)
    description: Prod Management Subnet Access Type (Private or Public)
    required: false
    visible: true
    default: true
  prod_management_subnet_prohibit_public_ip_on_vnic:
    type: boolean
    title: Prod Management Subnet Access Type (Private or Public)
    description: Prod Management Subnet Access Type (Private or Public)
    required: false
    visible: true
    default: true
  prod_management_project_tag:
    type: oci:identity:tag:value
    title: Tags to be assigned to resources created by terraform
    description: Tags to be assigned to resources created by terraform
    required: false
    visible: true
  prod_trust_subnet_display_name:
    type: string
    title: Prod Trust Subnet Display Name
    description: Prod Trust Subnet Display Name
    required: false
    visible: true
    default: sn-prod-hub-trust-uas2
  prod_trust_subnet_dns_label:
    type: string
    title: Prod Trust Subnet DNS Label
    description: Prod Trust Subnet DNS Label
    required: false
    visible: true
    default: trustuas2
  prod_trust_subnet_cidr_block:
    type: string
    title: Prod Trust Subnet Cidr Block
    description: Prod Trust Subnet Cidr Block
    required: false
    visible: true
    default: 20.20.3.0/24
  prod_trust_subnet_prohibit_internet_ingress:
    type: boolean
    title: Prod Trust Subnet Access Type (Private or Public)
    description: Prod Trust Subnet Access Type (Private or Public)
    required: false
    visible: true
    default: true
  prod_trust_subnet_prohibit_public_ip_on_vnic:
    type: boolean
    title: Prod Trust Subnet Access Type (Private or Public)
    description: Prod Trust Subnet Access Type (Private or Public)
    required: false
    visible: true
    default: true
  prod_trust_project_tag:
    type: oci:identity:tag:value
    title: Tags to be assigned to resources created by terraform
    description: Tags to be assigned to resources created by terraform
    required: false
    visible: true
  vcn_prod_hub_jde_uas2_servicegateway_private_display_name:
    type: string
    title: Prod HUB VCN Service Gateway Display Name
    description: Prod HUB VCN Service Gateway Display Name
    required: false
    visible: true
    default: vcn_prod_hub_jde_uas2_servicegateway_private
  vcn_prod_hub_jde_uas2_natgateway_display_name:
    type: string
    title: Prod HUB VCN NAT Gateway Display Name
    description: Prod HUB VCN NAT Gateway Display Name
    required: false
    visible: true
    default: vcn_prod_hub_jde_uas2_natgateway
  vcn_prod_hub_jde_uas2_natgateway_block_traffic:
    type: boolean
    title: Block the traffic in NAT gateway on creation
    description: Block the traffic in NAT gateway on creation
    required: false
    visible: true
    default: false
  vcn_prod_hub_jde_uas2_natgateway_public_ip_lifetime:
    type: string
    title: Reserved IP Address will be created for NAT Gateway
    description: Reserved IP Address will be created for NAT Gateway
    required: false
    visible: true
    default: RESERVED
  vcn_prod_hub_jde_uas2_intgw_display_name:
    type: string
    title: Prod HUB VCN Internet Gateway Display Name
    description: Prod HUB VCN Internet Gateway Display Name
    required: false
    visible: true
    default: vcn_prod_hub_jde_uas2_intgw
  vcn_prod_hub_jde_uas2_intgw_enabled:
    type: boolean
    title: Is Prod HUB intgw enabled
    description: Is Prod HUB intgw enabled
    required: false
    visible: true
    default: true
  vcn_prod_hub_jde_uas2_routetable_untrust_display_name:
    type: string
    title: Prod HUB VCN Untrust Route Table
    description: Prod HUB VCN Untrust Route Table
    required: false
    visible: true
    default: vcn_prod_hub_jde_uas2_routetable_untrust
  vcn_prod_hub_jde_uas2_routetable_private_management_display_name:
    type: string
    title: Prod HUB VCN Managment Route Table
    description: Prod HUB VCN Managment Route Table
    required: false
    visible: true
    default: vcn_prod_hub_jde_uas2_routetable_private_management
  vcn_prod_hub_jde_uas2_routetable_private_trust_display_name:
    type: string
    title: Prod HUB VCN Trust Route Table
    description: Prod HUB VCN Trust Route Table
    required: false
    visible: true
    default: vcn_prod_hub_jde_uas2_routetable_private_trust
  vcn_prod_hub_jde_uas2_routetable_private_ha_display_name:
    type: string
    title: Prod HUB VCN HA Private Route Table
    description: Prod HUB VCN HA Private Route Table
    required: false
    visible: true
    default: vcn_prod_hub_jde_uas2_routetable_private_ha
  drg_display_name:
    type: string
    title: DRG Display Name
    description: DRG Display Name
    required: false
    visible: true
    default: ash-prod-drg-uas2
  vcn_prod_hub_jde_uas2_drg_attachment_display_name:
    type: string
    title: Prod DRG Attachment Display Name
    description: Prod DRG Attachment Display Name
    required: false
    visible: true
    default: vcn_prod_hub_jde_uas2_drg_attachment
  vcn_prod_hub_jde_uas2_seclist_private_trust_display_name:
    type: string
    title: Prod HUB VCN trust Private Security List Display Name
    description: Prod HUB VCN trust Private Security List Display Name
    required: false
    visible: true
    default: vcn_prod_hub_jde_uas2_seclist_private_trust
  vcn_prod_hub_jde_uas2_seclist_private_ha_display_name:
    type: string
    title: Prod HUB VCN HA Subnet Private Security List Display Name
    description: Prod HUB VCN HA Subnet Private Security List Display Name
    required: false
    visible: true
    default: vcn_prod_hub_jde_uas2_seclist_private_ha
  vcn_prod_hub_jde_uas2_seclist_private_management_display_name:
    type: string
    title: Prod HUB VCN management Subnet Private Security List Display Name
    description: Prod HUB VCN management Subnet Private Security List Display Name
    required: false
    visible: true
    default: vcn_prod_hub_jde_uas2_seclist_private_management
  vcn_prod_hub_jde_uas2_seclist_untrust_display_name:
    type: string
    title: Prod HUB VCN untrust Subnet Security List Display Name
    description: Prod HUB VCN untrust Subnet Security List Display Name
    required: false
    visible: true
    default: vcn_prod_hub_jde_uas2_seclist_untrust
  vcn_prod_hub_jde_uas2_seclist_private_is_stateless:
    type: boolean
    title: Prod HUB VCN Private Security List is Stateless?
    description: Prod HUB VCN Private Security List is Stateless?
    required: false
    visible: true
    default: false
